const Transaction = [
    {
      id: "TXN001",
      customerName: "John Doe",
      amount: 150.75,
      currency: "USD",
      paymentMethod: "Credit Card",
      status: "Completed",
      date: "2025-01-05T10:30:00Z",
      description: "Purchase of electronics",
      transactionType: "Debit",
    },
    {
      id: "TXN002",
      customerName: "Jane Smith",
      amount: 75.5,
      currency: "USD",
      paymentMethod: "PayPal",
      status: "Pending",
      date: "2025-01-04T12:15:00Z",
      description: "Payment for services",
      transactionType: "Debit",
    },
    // {
    //   id: "TXN003",
    //   customerName: "Alex Johnson",
    //   amount: 500.0,
    //   currency: "USD",
    //   paymentMethod: "Bank Transfer",
    //   status: "Failed",
    //   date: "2025-01-03T14:45:00Z",
    //   description: "Refund for order #4567",
    //   transactionType: "Credit",
    // },
    // {
    //   id: "TXN004",
    //   customerName: "Emily Davis",
    //   amount: 200.25,
    //   currency: "USD",
    //   paymentMethod: "Credit Card",
    //   status: "Completed",
    //   date: "2025-01-02T16:00:00Z",
    //   description: "Subscription payment",
    //   transactionType: "Debit",
    // },
    // {
    //   id: "TXN005",
    //   customerName: "Michael Brown",
    //   amount: 350.0,
    //   currency: "USD",
    //   paymentMethod: "Crypto",
    //   status: "Completed",
    //   date: "2025-01-01T18:20:00Z",
    //   description: "Purchase of software license",
    //   transactionType: "Debit",
    // },
  ];
  
  export default Transaction;
  